# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import minecraft_pb2 as minecraft__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in minecraft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinecraftEnvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/minecraft.MinecraftEnv/Health',
                request_serializer=minecraft__pb2.Empty.SerializeToString,
                response_deserializer=minecraft__pb2.HealthResp.FromString,
                _registered_method=True)
        self.BatchCreate = channel.unary_unary(
                '/minecraft.MinecraftEnv/BatchCreate',
                request_serializer=minecraft__pb2.BatchCreateReq.SerializeToString,
                response_deserializer=minecraft__pb2.BatchCreateResp.FromString,
                _registered_method=True)
        self.EnvStatus = channel.unary_unary(
                '/minecraft.MinecraftEnv/EnvStatus',
                request_serializer=minecraft__pb2.EnvIdReq.SerializeToString,
                response_deserializer=minecraft__pb2.EnvStatusResp.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/minecraft.MinecraftEnv/Reset',
                request_serializer=minecraft__pb2.FastResetReq.SerializeToString,
                response_deserializer=minecraft__pb2.ResetResp.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/minecraft.MinecraftEnv/Step',
                request_serializer=minecraft__pb2.StepReq.SerializeToString,
                response_deserializer=minecraft__pb2.StepResp.FromString,
                _registered_method=True)
        self.SubmitStep = channel.unary_unary(
                '/minecraft.MinecraftEnv/SubmitStep',
                request_serializer=minecraft__pb2.StepReq.SerializeToString,
                response_deserializer=minecraft__pb2.StepResultResp.FromString,
                _registered_method=True)
        self.GetStepResult = channel.unary_unary(
                '/minecraft.MinecraftEnv/GetStepResult',
                request_serializer=minecraft__pb2.EnvIdReq.SerializeToString,
                response_deserializer=minecraft__pb2.StepResultResp.FromString,
                _registered_method=True)
        self.CloseEnv = channel.unary_unary(
                '/minecraft.MinecraftEnv/CloseEnv',
                request_serializer=minecraft__pb2.EnvIdReq.SerializeToString,
                response_deserializer=minecraft__pb2.CloseResp.FromString,
                _registered_method=True)
        self.GetResetResult = channel.unary_unary(
                '/minecraft.MinecraftEnv/GetResetResult',
                request_serializer=minecraft__pb2.GetResetResultReq.SerializeToString,
                response_deserializer=minecraft__pb2.ResetResp.FromString,
                _registered_method=True)


class MinecraftEnvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreate(self, request, context):
        """批量创建
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnvStatus(self, request, context):
        """查询环境状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """同步 reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """同步 step（调试用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitStep(self, request, context):
        """异步 step：提交
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStepResult(self, request, context):
        """异步 step：轮询结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseEnv(self, request, context):
        """关闭环境
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResetResult(self, request, context):
        """获取异步 reset 结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinecraftEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=minecraft__pb2.Empty.FromString,
                    response_serializer=minecraft__pb2.HealthResp.SerializeToString,
            ),
            'BatchCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreate,
                    request_deserializer=minecraft__pb2.BatchCreateReq.FromString,
                    response_serializer=minecraft__pb2.BatchCreateResp.SerializeToString,
            ),
            'EnvStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.EnvStatus,
                    request_deserializer=minecraft__pb2.EnvIdReq.FromString,
                    response_serializer=minecraft__pb2.EnvStatusResp.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=minecraft__pb2.FastResetReq.FromString,
                    response_serializer=minecraft__pb2.ResetResp.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=minecraft__pb2.StepReq.FromString,
                    response_serializer=minecraft__pb2.StepResp.SerializeToString,
            ),
            'SubmitStep': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitStep,
                    request_deserializer=minecraft__pb2.StepReq.FromString,
                    response_serializer=minecraft__pb2.StepResultResp.SerializeToString,
            ),
            'GetStepResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStepResult,
                    request_deserializer=minecraft__pb2.EnvIdReq.FromString,
                    response_serializer=minecraft__pb2.StepResultResp.SerializeToString,
            ),
            'CloseEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseEnv,
                    request_deserializer=minecraft__pb2.EnvIdReq.FromString,
                    response_serializer=minecraft__pb2.CloseResp.SerializeToString,
            ),
            'GetResetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResetResult,
                    request_deserializer=minecraft__pb2.GetResetResultReq.FromString,
                    response_serializer=minecraft__pb2.ResetResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minecraft.MinecraftEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minecraft.MinecraftEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MinecraftEnv(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/Health',
            minecraft__pb2.Empty.SerializeToString,
            minecraft__pb2.HealthResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/BatchCreate',
            minecraft__pb2.BatchCreateReq.SerializeToString,
            minecraft__pb2.BatchCreateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnvStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/EnvStatus',
            minecraft__pb2.EnvIdReq.SerializeToString,
            minecraft__pb2.EnvStatusResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/Reset',
            minecraft__pb2.FastResetReq.SerializeToString,
            minecraft__pb2.ResetResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/Step',
            minecraft__pb2.StepReq.SerializeToString,
            minecraft__pb2.StepResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/SubmitStep',
            minecraft__pb2.StepReq.SerializeToString,
            minecraft__pb2.StepResultResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStepResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/GetStepResult',
            minecraft__pb2.EnvIdReq.SerializeToString,
            minecraft__pb2.StepResultResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/CloseEnv',
            minecraft__pb2.EnvIdReq.SerializeToString,
            minecraft__pb2.CloseResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minecraft.MinecraftEnv/GetResetResult',
            minecraft__pb2.GetResetResultReq.SerializeToString,
            minecraft__pb2.ResetResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
